### ISSUE TITLE
error returned from database: no such column: sys_menu.is_log

### ISSUE THREAD

**Issue by tonsiasy** [lingdu1234/poem_admin#2]
我修改了 db 默认driver 为sqlite。
cargo run 时报一下错误： 
INFO app::utils::api_utils: 初始化时获取路由API失败:Query(
    "error returned from database: no such column: sys_menu.is_log",
)

**Comment by tonsiasy** [comment]
sea-orm-cli migrate fresh

**Comment by lingdu1234** [comment]
重新添加了个  空的  sqlite 文件了 ，以前的数据库没有更新
