### ISSUE TITLE
数据库可否改成mysql

### ISSUE THREAD

**Issue by xtuyaowu** [lingdu1234/poem_admin#3]
lingdu：
          很棒的项目，可否加个好友讨论一下，谢谢！QQ：1840658279  

祝好！

**Comment by lingdu1234** [comment]
可以啊，自己修改.env文件的 DATABASE_URL 为自己的mysql地址，
mysql pgsql sqlite都支持的 ，该readme的时候 把数据库迁移无意间删除了
## 数据迁移
1. 安装sea-orm cli 工具 `cargo install sea-orm-cli`
2. 在 .env中设置数据库地址
3. 运行迁移命令：`sea-orm-cli migrate up`
然后在 config/config.toml设置对应数据库地址就可以了
