### ISSUE TITLE
可以请教下 sys_api_db表的作用是什么吗？没看懂

### ISSUE THREAD

**Issue by aqrun** [lingdu1234/poem_admin#6]
![image](https://user-images.githubusercontent.com/4224867/186421302-d1d0190b-d672-44f6-8b54-8a1968bb20e8.png)

**Comment by lingdu1234** [comment]
做了个  api 关联数据表  内存缓存数据的  根据api请求方法 关联数据库缓存  更新的时候 清除缓存  不用的话  把配置文件里面的配置设置为false就好了

**Comment by aqrun** [comment]
哦 谢谢解答 
后台配置主要是 权限查询 使用了 apidb是吧
![image](https://user-images.githubusercontent.com/4224867/186435453-e9cc4888-238f-43af-aadf-58983e1cb66a.png)
缓存参数对应的是 CFG.server.cache_time > 0 是吗
这块看的还是一知半解 没理清。我再研究下。。^_^
